### ISSUE TITLE
New crashes after fully implicit patch warnings

### ISSUE THREAD

**Issue by rob-rb** [gcherchi/InteractiveAndRobustMeshBooleans#30]
Since I use the latest version I have no more crashes with high valence meshes but I have now crashes in really "easy" situations. Whenever I get the warning 
"
WARNING: the arrangement contains a fully implicit patch that requires exact rationals for evaluation. This version of the code does not support rationals, therefore the output result may contain open boundaries.
"
the program crashes.
[bad2.zip](https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/files/13723666/bad2.zip)

**Comment by sloriot** [comment]
bad1.obj is self-intersecting, even if the self-intersection is not in the intersection area it might be a problem for the code. You should try to fix it and report if you still have a problem after that.

**Comment by rob-rb** [comment]
merci seb for your analysis. I was able to fix it "rootwise".

**Comment by gcherchi** [comment]
Hi,
we are working to include the fix for that warning in the official public version of the Booleans code.
As @sloriot suggested, your models are not intersection-free (thank you Sebastien for your support!). Note that if you compile our code, you obtain an executable file called "mesh_booleans_inputcheck"; you can use it to check if your models are suitable input for our code.
Regards,
Gianmarco

**Comment by rob-rb** [comment]
Actually the input_check passed. No intersections were found. But when testing the triangles for dot-normals < -0.99 I get a lot of triangle-pairs.

**Comment by gcherchi** [comment]
I tried your models, and the input checker failed on bad1.obj. 
BTW, remember that we compute the intersections in an exact way (by using exact predicates), while the triangle normals are not robust in our context (e.g.: you cannot trust the normal of an almost degenerate triangle).
