### ISSUE TITLE
 Error "unable to calculate ray for this patch"

### ISSUE THREAD

**Issue by gianpaolopalma** [gcherchi/InteractiveAndRobustMeshBooleans#8]
Hi, by testing your code with the intersection of two manifold meshes (with a tubular shape) I get the error "unable to calculate ray for this patch". What features should have the meshes to avoid this error?

**Comment by gcherchi** [comment]
Hi,
input meshes must be manifold, watertight and with no self-intersections and well oriented.
If your meshes satisfy these requirements, please send us your models.

**Comment by gianpaolopalma** [comment]
Thanks for the answer. The meshes satisfy all the requirements. Attached there are the two meshes. Consider that if I comment line https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/blob/8209384edf2961873b781a221214a4024d2f9316/code/booleans.cpp#L597 the program ends computing the right intersection.
[meshes.zip](https://github.com/gcherchi/InteractiveAndRobustMeshBooleans/files/10208359/meshes.zip)

**Comment by gcherchi** [comment]
Hi Giampaolo,
I tested your input meshes, and they require the portion of our pipeline that involves rational numbers (as described in our paper, at the end of section 5.1). 
In the version that we released, we omitted ray casting with exact rationals because the code was convoluted and it was also never necessary in all our tests. As you noticed, the code can still produce a final result, but we suggest you to check the output to be sure it is topologically correct (you can use the checker we just added).
